"""Initial migration

Revision ID: 3ca87d1613fe
Revises: 
Create Date: 2023-08-02 22:45:42.522872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca87d1613fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text("(CURRENT_DATE + '1 day'::interval)"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True,
               existing_server_default=sa.text("(CURRENT_DATE + '1 day'::interval)"))
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
